version: "3.11"

services:
  fastapi:
    build: .
    container_name: fast
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
      - media_volume:/uploads
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://DB_USER:DB_PASSWORD@DB_HOST:DB_PORT/DB_NAME
    ports:
      - '8000:8000'
    depends_on:
      - db
      - celery
      - redis
  db:
    container_name: database
    image: postgres:15.0-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  celery:
    build: .
    command: celery -A tasks.config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379


volumes:
  media_volume:
  redis_data: