version: "3.11"

services:
  fastapi:
    build: .
    container_name: fast
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 #["/app/docker/app.sh"]
    volumes:
      - .:/app
      - media_volume:/uploads
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://DB_USER:DB_PASSWORD@DB_HOST:DB_PORT/DB_NAME
    ports:
      - '8000:8000'
    depends_on:
      - db
      - celery
      - redis
  db:
    container_name: database
    image: postgres:15.0-alpine
    command: -p 5432
    expose:
      - 5432
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  celery:
    build: .
    container_name: celery
    command: celery --app=tasks.tasks:celery worker --loglevel=INFO #["/app/docker/celery.sh", "celery"]
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis
    command: --port 6379
    volumes:
      - redis_data:/data/
    expose:
      - 6379


volumes:
  media_volume:
  redis_data: